name: Tests

on:
  push:
    branches: [ production, develop, release/**, feature/**, hotfix/** ]
  pull_request:
    branches: [ production, develop, release/**, feature/**, hotfix/** ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
